DROP DATABASE IF EXISTS book_list;
CREATE DATABASE book_list;

USE book_list;

DROP TABLE IF EXISTS Binding_details;
CREATE TABLE Binding_Details(
   Id INT NOT NULL AUTO_INCREMENT,
   Type VARCHAR(50),
   PRIMARY KEY(Id)
);

DROP TABLE IF EXISTS Categor_details;
CREATE TABLE Category_Details(
   Id INT NOT NULL AUTO_INCREMENT,
   Name VARCHAR(50),
   PRIMARY KEY(Id)
);

DROP TABLE IF EXISTS Languages;
CREATE TABLE Laguages(
   Id INT NOT NULL AUTO_INCREMENT,
   WrittenLanguage VARCHAR(50),
   PRIMARY KEY(Id)
);

DROP TABLE IF EXISTS Nationalites;
CREATE TABLE Nationalites(
   Id INT NOT NULL AUTO_INCREMENT,
   Nationality VARCHAR(50),
   PRIMARY KEY(Id)
);

DROP TABLE IF EXISTS Author_Details;
CREATE TABLE Author_Details(
   Id INT NOT NULL AUTO_INCREMENT,
   Name VARCHAR(50),
   BooksWritten INT,
   Id_1 INT NOT NULL,
   PRIMARY KEY(Id),
   FOREIGN KEY(Id_1) REFERENCES Nationalites(Id)
);

DROP TABLE IF EXISTS Book_Details;
CREATE TABLE Book_Details(
   Id INT NOT NULL AUTO_INCREMENT,
   DatePublished DATE,
   Title VARCHAR(50),
   ISBN10 INT,
   Id_1 INT NOT NULL,
   Id_2 INT NOT NULL,
   PRIMARY KEY(Id),
   UNIQUE(ISBN),
   FOREIGN KEY(Id_1) REFERENCES Binding_Details(Id),
   FOREIGN KEY(Id_2) REFERENCES Author_Details(Id)
);

DROP TABLE IF EXISTS Wishlist;
CREATE TABLE WishList(
   Id INT NOT NULL AUTO_INCREMENT,
   Id_1 INT NOT NULL,
   PRIMARY KEY(Id),
   UNIQUE(Id_1),
   FOREIGN KEY(Id_1) REFERENCES Book_Details(Id)
);

DROP TABLE IF EXISTS Owned;
CREATE TABLE Owned(
   Id INT NOT NULL AUTO_INCREMENT,
   Id_1 INT NOT NULL,
   PRIMARY KEY(Id),
   UNIQUE(Id_1),
   FOREIGN KEY(Id_1) REFERENCES Book_Details(Id)
);

DROP TABLE IF EXISTS Lost;
CREATE TABLE Lost(
   Id INT NOT NULL AUTO_INCREMENT,
   Id_1 INT NOT NULL,
   PRIMARY KEY(Id),
   UNIQUE(Id_1),
   FOREIGN KEY(Id_1) REFERENCES Book_Details(Id)
);

DROP TABLE IF EXISTS isInCategory;
CREATE TABLE isInCategory(
   Id INT NOT NULL AUTO_INCREMENT,
   Id_1 INT,
   PRIMARY KEY(Id, Id_1),
   FOREIGN KEY(Id) REFERENCES Book_Details(Id),
   FOREIGN KEY(Id_1) REFERENCES Category_Details(Id)
);

DROP TABLE IF EXISTS isWrittenIn;
CREATE TABLE isWrittenIn(
   Id INT NOT NULL AUTO_INCREMENT,
   Id_1 INT,
   PRIMARY KEY(Id, Id_1),
   FOREIGN KEY(Id) REFERENCES Book_Details(Id),
   FOREIGN KEY(Id_1) REFERENCES Laguages(Id)
);
